### ISSUE TITLE
camelot is gone for good

### ISSUE THREAD

**Issue by umlaeute** [bplaum/gmerlin#5]
gmerlin no longer includes `Camelot`, but the README still mentions it: https://github.com/bplaum/gmerlin/blob/68cddb0791c90bd32bcdd7155cb67e3e59bf185e/README#L31-L32

**Comment by umlaeute** [comment]
and probably the `alsamixer` should be removed as well...

**Comment by bplaum** [comment]
Thanks for the notice, I've updated README and will continue to do so.
