### ISSUE TITLE
`autogen.sh`/`autoreconf` fail

### ISSUE THREAD

**Issue by umlaeute** [bplaum/gmerlin#7]
There's a leftover mention of `apps/cmdlinerecorder/Makefile` in 

https://github.com/bplaum/gmerlin/blob/a3d7f4ff36d038f89766e133adccfd15166ffda0/configure.ac#L871

since the `-apps/cmdlinerecorder/` directory has been removed, the project can no longer be bootstrapped.

**Comment by bplaum** [comment]
Fixed.
